##macro file for calculation of missed tracks correction
/run/initialize
##use real kinematics
/PA/generator/useGenerated true
/PA/generator/setInFile run5055kine.txt
#turn of pion, kaon decay: included in SIMC
/process/inactivate Decay pi+
/process/inactivate Decay kaon+
/run/physicsModified

##specify particle type, central momentum, and output file name
/PA/generator/momentum 5 GeV
/gun/particle proton
/analysis/setFileName proton5GeV1000.root
/run/beamOn 1000
